Repository iamarunbrahma/vision-parse, pull requests merged in 2025-01, with the labels that each got.

#10 feat: Add benchmarking framework with accuracy comparison for Vision Parse and Markitdown
  benchmarks/benchmark_results.md
  benchmarks/ground_truth.md
  benchmarks/quantum_computing.pdf
  benchmarks/requirements.txt
  benchmarks/scoring.py
  src/vision_parse/markdown_prompt.j2
Labels: enhancement, size:L

#11 Update README.md
  README.md
Labels: documentation, size:XS, lgtm

#13 Support Azure-Openai
  README.md
  pyproject.toml
  src/vision_parse/llm.py
  tests/test_llm.py
  uv.lock
Labels: documentation, enhancement, size:L

#15 docs: updated README.md
  README.md
Labels: size:M

#16 docs: minor changes in README.md related to inline links
  README.md
Labels: documentation, size:S

#17 docs: Updated README and added FAQ documentation
  README.md
  docs/config.md
  docs/examples/gemini_demo.ipynb
  docs/examples/ollama_demo.ipynb
  docs/examples/openai_demo.ipynb
  docs/faq.md
  docs/ollama_setup.md
Labels: documentation, size:M

#18 Update config.md
  docs/config.md
Labels: documentation, size:XS

#20 feat: Add test method for DeepSeek models and update dependencies
  Makefile
  docs/examples/deepseek_demo.ipynb
  pyproject.toml
  src/vision_parse/llm.py
  tests/test_llm.py
  uv.lock
Labels: enhancement, size:L

#21 update format-nb in Makefile and benchmarking section in README.md
  Makefile
  README.md
Labels: documentation, size:XS

#22 Added Docker Setup Guide
  README.md
  docs/docker_setup.md
  uv.lock
Labels: documentation, size:M
