Repository iamarunbrahma/vision-parse, pull requests merged in 2025-02, with the labels that each got.

#24 Removed stream args from beta.chat.completions.parse in OpenAI API
  src/vision_parse/llm.py
Labels: documentation, size:XS

#25 Add Gradio demo application for Vision Parse PDF extraction
  docs/examples/gradio_app.py
Labels: documentation, size:L

#26 Update Docker and README documentation for improved clarity and setup instructions
  Dockerfile
  README.md
  docs/docker_setup.md
Labels: documentation, size:M

#27 Add detailed model configuration documentation for Vision Parse
  README.md
  docs/model_config.md
Labels: documentation, size:S

#30 [FEATURE]: Support for deepseek-r1 from ollama
  README.md
  src/vision_parse/constants.py
  tests/test_llm.py
Labels: enhancement, size:M, lgtm

#31 Refine markdown prompt template text extraction instructions
  src/vision_parse/markdown_prompt.j2
Labels: documentation, size:XS

#32 Add Streamlit demo application for Vision Parse PDF extraction
  docs/examples/streamlit_app.py
Labels: documentation, size:L
